name: ginjuice
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.1.2
  flutter_native_splash: ^2.3.0
  sizer: ^2.0.15
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.4
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  open_mail_app: ^0.4.5
  shared_preferences: ^2.1.1
  google_nav_bar: ^5.0.6
  dio: ^5.1.2
  # pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.2.0
  shimmer: ^3.0.0
  path_provider: ^2.0.15
  fluttermoji: ^1.0.2
  lottie: ^2.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  flutter_gen_runner:
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  custom_lint:
  riverpod_lint: ^1.3.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/

# Flutter Native Splash Screen Configuration
flutter_native_splash:
  color: "#261d1d"
  image: assets/images/logo.png

flutter_gen:
  output: lib/core/utils

  integrations:
    lottie: true